import { Inter, DM_Serif_Display } from "next/font/google";
import "./globals.css";
import "./typography.css";
import SmoothScroll from "./SmoothScroll";

export const metadata = {
  title: "RBD3",
  description: "Generated by fantaz",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-body",
  display: "swap",
});

const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-display",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${dmSerif.variable}`}>
      <body>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
