/**
 * Tours — canonical structure for /tours, /tours/[slug] and the bespoke page.
 *
 * Copy lives under the `tourItems.<key>` namespace in messages.
 * `gallery` here is an array of image paths; captions are `tourItems.<key>.gallery`
 * and are matched by index.
 *
 * STRUCTURE ONLY — no user-facing copy lives here.
 * Every string a visitor reads is in src/messages/<locale>.json.
 */

const tours = [
  {
    key: "blue-lagoon-three-islands",
    depositEur: 30000,
    restEur: 110000,
    minPrice: 800,
    maxPrice: 1100,
    durationHours: 6,
    touristType: ["Family", "Couple", "Group"],
    thumb: "/images/tours/lagoon/krknjasi-1.jpeg",
    thumbAlt: "Rebelde boats in the Blue Lagoon, Croatia",
    hero: "/images/tours/lagoon/krknjasi-1.jpeg",
    mainImg: "/images/tours/lagoon/large-thumb.jpg",
    subImg:
      "/images/tours/lagoon/gallery/rebelde boats three islands tour 07.jpg",
    ctaImg: "/images/tours/lagoon/cta-thumb.jpg",
    gallery: [
      "/images/tours/lagoon/gallery/rebelde boats three islands tour 01.jpeg",
      "/images/tours/lagoon/gallery/rebelde boats three islands tour 02.jpeg",
      "/images/tours/lagoon/gallery/rebelde boats three islands tour 03.jpg",
      "/images/tours/lagoon/gallery/rebelde boats three islands tour 04.jpg",
      "/images/tours/lagoon/gallery/rebelde boats three islands tour 05.jpg",
      "/images/tours/lagoon/gallery/rebelde boats three islands tour 06.jpg",
      "/images/tours/lagoon/gallery/rebelde boats three islands tour 07.jpg",
      "/images/tours/lagoon/gallery/rebelde boats three islands tour 08.jpg",
    ],
    faqIds: [
      "lagoon-q1",
      "lagoon-q3",
      "lagoon-q6",
      "trogir-q1",
      "general-q5",
      "general-q1",
    ],
    relatedTourKeys: [
      "blue-cave-five-islands",
      "hvar-pakleni-islands",
      "bol-hvar-pakleni",
    ],
  },
  {
    key: "blue-cave-five-islands",
    depositEur: 40000,
    restEur: 110000,
    minPrice: 1500,
    maxPrice: 1750,
    durationHours: 10,
    touristType: ["Adventurer", "Couple", "Family", "Group"],
    thumb: "/images/tours/blue-cave/large-thumb.jpg",
    thumbAlt: "Rebelde boats guests in the Blue Cave, Croatia",
    hero: "/images/tours/blue-cave/hero.jpg",
    mainImg: "/images/tours/blue-cave/large-thumb.jpg",
    subImg: "/images/tours/blue-cave/small-thumb.jpg",
    ctaImg: "/images/tours/blue-cave/cta-thumb.jpg",
    gallery: [
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 01.jpeg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 02.jpg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 03.jpg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 04.jpg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 05.jpg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 06.jpg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 07.jpg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 08.jpg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 09.jpeg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 10.jpg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 11.jpg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 12.jpeg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 13.jpg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 14.jpg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 15.jpg",
      "/images/tours/blue-cave/gallery/rebelde boats five islands tour 16.jpg",
    ],
    faqIds: [
      "bluecave-q1",
      "bluecave-q2",
      "bluecave-q5",
      "fiveislands-q1",
      "fiveislands-q2",
      "general-q5",
    ],
    relatedTourKeys: [
      "hvar-pakleni-islands",
      "bol-hvar-pakleni",
      "blue-lagoon-three-islands",
    ],
  },
  {
    key: "hvar-pakleni-islands",
    depositEur: 40000,
    restEur: 100000,
    minPrice: 1400,
    maxPrice: 1650,
    durationHours: 9,
    touristType: ["Couple", "Group"],
    thumb: "/images/tours/hvar-pakleni/main-thumb.jpg",
    thumbAlt: "Overlook of Hvar and Pakleni Islands, Croatia - Rebelde Boats",
    hero: "/images/tours/hvar-pakleni/main-thumb.jpg",
    mainImg: "/images/tours/hvar-pakleni/large-thumb.jpg",
    subImg: "/images/tours/hvar-pakleni/small-thumb.jpg",
    ctaImg: "/images/tours/hvar-pakleni/cta-thumb.jpg",
    gallery: [
      "/images/tours/hvar-pakleni/gallery/rebelde boats hvar pakleni tour 01.jpg",
      "/images/tours/hvar-pakleni/gallery/rebelde boats hvar pakleni tour 02.jpeg",
      "/images/tours/hvar-pakleni/gallery/rebelde boats hvar pakleni tour 09.jpg",
      "/images/tours/hvar-pakleni/gallery/rebelde boats hvar pakleni tour 10.jpg",
      "/images/tours/hvar-pakleni/gallery/rebelde boats hvar pakleni tour 03.jpg",
      "/images/tours/hvar-pakleni/gallery/rebelde boats hvar pakleni tour 04.jpeg",
      "/images/tours/hvar-pakleni/gallery/rebelde boats hvar pakleni tour 05.jpg",
      "/images/tours/hvar-pakleni/gallery/rebelde boats hvar pakleni tour 06.jpg",
      "/images/tours/hvar-pakleni/gallery/rebelde boats hvar pakleni tour 07.jpg",
      "/images/tours/hvar-pakleni/gallery/rebelde boats hvar pakleni tour 08.jpg",
    ],
    faqIds: [
      "hvar-q1",
      "hvar-q2",
      "pakleni-q1",
      "pakleni-q2",
      "general-q5",
      "general-q1",
    ],
    relatedTourKeys: [
      "bol-hvar-pakleni",
      "blue-cave-five-islands",
      "blue-lagoon-three-islands",
    ],
  },
  {
    key: "bol-hvar-pakleni",
    depositEur: 40000,
    restEur: 100000,
    minPrice: 1400,
    maxPrice: 1650,
    durationHours: 9,
    touristType: ["Family", "Group"],
    thumb: "/images/tours/bol-hvar-pakleni/main-thumb.jpg",
    thumbAlt: "View of Golden Horn Beach, Bol, Croatia - Rebelde Boats",
    hero: "/images/tours/bol-hvar-pakleni/main-thumb.jpg",
    mainImg: "/images/tours/bol-hvar-pakleni/large-thumb.jpg",
    subImg: "/images/tours/bol-hvar-pakleni/small-thumb.jpeg",
    ctaImg: "/images/tours/bol-hvar-pakleni/cta-thumb.jpg",
    gallery: [
      "/images/tours/bol-hvar-pakleni/gallery/rebelde boats bol hvar pakleni tour 01.jpg",
      "/images/tours/bol-hvar-pakleni/gallery/rebelde boats bol hvar pakleni tour 02.jpg",
      "/images/tours/bol-hvar-pakleni/gallery/rebelde boats bol hvar pakleni tour 03.jpg",
      "/images/tours/bol-hvar-pakleni/gallery/rebelde boats bol hvar pakleni tour 04.jpg",
      "/images/tours/bol-hvar-pakleni/gallery/rebelde boats bol hvar pakleni tour 05.jpg",
      "/images/tours/bol-hvar-pakleni/gallery/rebelde boats bol hvar pakleni tour 06.jpg",
      "/images/tours/bol-hvar-pakleni/gallery/rebelde boats bol hvar pakleni tour 07.jpg",
      "/images/tours/bol-hvar-pakleni/gallery/rebelde boats bol hvar pakleni tour 08.jpg",
      "/images/tours/bol-hvar-pakleni/gallery/rebelde boats bol hvar pakleni tour 09.jpg",
      "/images/tours/bol-hvar-pakleni/gallery/rebelde boats bol hvar pakleni tour 10.jpg",
    ],
    faqIds: [
      "bol-q1",
      "bol-q2",
      "bol-q3",
      "hvar-q1",
      "pakleni-q1",
      "general-q5",
    ],
    relatedTourKeys: [
      "hvar-pakleni-islands",
      "blue-cave-five-islands",
      "blue-lagoon-three-islands",
    ],
  },
];

export default tours;

export const tourKeys = tours.map((t) => t.key);
export const getTour = (key) => tours.find((t) => t.key === key);
